/* Pixel art desenhado à mão para a página da faby.

   Cada sprite é uma grade de caracteres: um caractere por pixel, '.'
   para transparente, e a paleta mapeia caractere -> cor. PixelSprite
   transforma isso em SVG, então escala sem borrar. */

export const SPRITES = {
  myMelody: {
    w: 26,
    h: 28,
    palette: { a: "#a45c79", b: "#fabed6", c: "#d6426e", d: "#f0628a", e: "#fffdfb", f: "#3a2a33", g: "#ffbad0", h: "#f39682" },
    rows: [
      "......a............a......",
      ".....aba..........aba.....",
      "....abbba........abbba....",
      "....abbba........abbba....",
      ".ccaccbbba......abbbbba...",
      "cdcccdcbba......abbbbba...",
      "cdcdcdcbba......abbbbba...",
      "cccccccbba......abbbbba...",
      "..cacbbbba......abbbbba...",
      "...abbbbbaaaaaaaabbbbba...",
      "...abbbaaabbbbbbaaabbba...",
      "...abbabbbbbbbbbbbbabba...",
      "....aabbbbbbbbbbbbbbaa....",
      "....abbbbbaaaaaabbbbba....",
      "...abbbbaaeeeeeeaabbbba...",
      "..abbbbaeeeeeeeeeeabbbba..",
      "..abbbaeeeeeeeeeeeeabbba..",
      "..abbbaeeffeeeeffeeabbba..",
      "..abbaeeeffeeeeffeeeabba..",
      "..abbaeeeffeeeeffeeeabba..",
      "..abbaggeeeehheeeeggabba..",
      "...abaggeeeehheeeeggaba...",
      "....abaeeeeaeeaeeeeaba....",
      ".....aaeeeeeaaeeeeeaa.....",
      "......aaeeeeeeeeeeaa......",
      ".......aaaeeeeeeaaa.......",
      "..........aaaaaa..........",
      "..........................",
    ],
  },
  /* mesma my melody, mas com os olhos revirados pra cima e a boca reta:
     as pupilas sobem para as linhas 16-17, a pálpebra vira um traço na 18 e
     a linha 22 fecha a boca num traço sem graça. */
  myMelodyDeboche: {
    w: 26,
    h: 28,
    palette: { a: "#a45c79", b: "#fabed6", c: "#d6426e", d: "#f0628a", e: "#fffdfb", f: "#3a2a33", g: "#ffbad0", h: "#f39682" },
    rows: [
      "......a............a......",
      ".....aba..........aba.....",
      "....abbba........abbba....",
      "....abbba........abbba....",
      ".ccaccbbba......abbbbba...",
      "cdcccdcbba......abbbbba...",
      "cdcdcdcbba......abbbbba...",
      "cccccccbba......abbbbba...",
      "..cacbbbba......abbbbba...",
      "...abbbbbaaaaaaaabbbbba...",
      "...abbbaaabbbbbbaaabbba...",
      "...abbabbbbbbbbbbbbabba...",
      "....aabbbbbbbbbbbbbbaa....",
      "....abbbbbaaaaaabbbbba....",
      "...abbbbaaeeeeeeaabbbba...",
      "..abbbbaeeeeeeeeeeabbbba..",
      "..abbbaeeffeeeeffeeabbba..",
      "..abbbaeeeeeeeeeeeeabbba..",
      "..abbaeeffffeeffffeeabba..",
      "..abbaeeeeeeeeeeeeeeabba..",
      "..abbaggeeeehheeeeggabba..",
      "...abaggeeeehheeeeggaba...",
      "....abaeeeeaaaaeeeeaba....",
      ".....aaeeeeeaaeeeeeaa.....",
      "......aaeeeeeeeeeeaa......",
      ".......aaaeeeeeeaaa.......",
      "..........aaaaaa..........",
      "..........................",
    ],
  },
  cinnamoroll: {
    w: 30,
    h: 26,
    palette: { a: "#7a96c4", b: "#ffffff", c: "#3f507a", d: "#ffbace", e: "#967896" },
    rows: [
      "..............................",
      "..............................",
      ".............aaaa.............",
      "...........aabbbbaa...........",
      "..........abbbbbbbba..........",
      ".........abbbbbbbbbba.........",
      "........abbbbbbbbbbbba........",
      "....aa..abbbbbbbbbbbba..aa....",
      "...abba.abbbbbbbbbbbba.abba...",
      "..abbbbabbbbccbbbbccbbabbbba..",
      "..abbbbabbbbccbbbbccbbabbbba..",
      "..abbbbabbbbccbbbbccbbabbbba..",
      ".abbbbbabbbbbbbbbbbbbbabbbbba.",
      ".abbbbbabbddbbbbbbddbbabbbbba.",
      ".abbbbbabbddbebbebddbbabbbbba.",
      ".abbbbbbabbbbbeebbbbbabbbbbba.",
      ".abbbbbbabbbbbbbbbbbbabbbbbba.",
      ".abbbbbbabbbbbbbbbbbbabbbbbba.",
      ".abbbbbbaabbbbbbbbbbaabbbbbba.",
      "..abbbba..abbbbbbbba..abbbba..",
      "..abbbba...aabbbbaa...abbbba..",
      "..abbbba.....aaaa.....abbbba..",
      "...abba................abba...",
      "....aa..................aa....",
      "..............................",
      "..............................",
    ],
  },
  keroppi: {
    w: 26,
    h: 22,
    palette: { a: "#3a7a3e", b: "#ffffff", c: "#2a2e2a", d: "#7ed957", e: "#ffa0b4", f: "#d84a60" },
    rows: [
      "......aaa........aaa......",
      ".....abbba......abbba.....",
      "....abbbbba....abbbbba....",
      "...abbbbbbba..abbbbbbba...",
      "...abbccbbbaaaabbccbbba...",
      "...abbccbbbaddabbccbbba...",
      "...abbccbbbaddabbccbbba...",
      "....abbbbbaddddabbbbba....",
      "....aabbbaddddddabbbaa....",
      "...addaaaddddddddaaadda...",
      "..adddddddddddddddddddda..",
      "..adddddddddddddddddddda..",
      "..adddddddddddddddddddda..",
      "..adeeddddddddddddddeeda..",
      "..adeeddddddddddddddeeda..",
      "..addddfddddddddddfdddda..",
      "...addddfddddddddfdddda...",
      "....addddffffffffdddda....",
      ".....adddddffffddddda.....",
      "......adddddddddddda......",
      ".......aaaddddddaaa.......",
      "..........aaaaaa..........",
    ],
  },
  heart: {
    w: 9,
    h: 8,
    palette: { a: "#ce4674", b: "#f06e96" },
    rows: [
      ".aaa.aaa.",
      "abbbabbba",
      "abbbabbba",
      "abbbbbbba",
      ".abbbbba.",
      "..abbba..",
      "...aba...",
      "....a....",
    ],
  },
  star: {
    w: 7,
    h: 7,
    palette: { a: "#e8ac2e", b: "#ffd666" },
    rows: [
      "...a...",
      "...aa..",
      ".aaba..",
      "aabbbaa",
      "..abaa.",
      "..aa...",
      "...a...",
    ],
  },
  bow: {
    w: 11,
    h: 7,
    palette: { a: "#d6608c", b: "#fa96ba" },
    rows: [
      "...........",
      "a.........a",
      "aaa..a..aaa",
      "abbaabaabba",
      "aaa..a..aaa",
      "a.........a",
      "...........",
    ],
  },
  cloud: {
    w: 14,
    h: 8,
    palette: { a: "#c5d8f4", b: "#ffffff" },
    rows: [
      "......aaaa....",
      ".....abbbba...",
      "....abbbbbba..",
      "..aaabbbbaaaa.",
      "aabbabbbabbbba",
      "abbbabbbabbbba",
      "aabbbbbbbbbbba",
      "..aaa.aaaaaaa.",
    ],
  },
  strawberry: {
    w: 9,
    h: 10,
    palette: { a: "#7cc260", b: "#58a046", c: "#c8384c", d: "#f05c6c", e: "#ffe2e2" },
    rows: [
      "....a....",
      ".........",
      ".bbbbbbb.",
      ".cbbabbc.",
      "cdddbeddc",
      "cdedddddc",
      "cdddddedc",
      "cddeddddc",
      ".ccdddcc.",
      "...ccc...",
    ],
  },
};
